apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hellok8s-go-http-daemonset
spec:
  selector:
    matchLabels:
      app: hellok8s
  template:
    metadata:
      labels:
        app: hellok8s
    spec:
      containers:
        - image: leigg/hellok8s:v1
          name: hellok8s