apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellok8s-logtest-json
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellok8s
  template:
    metadata:
      labels:
        app: hellok8s
    spec:
      containers:
        - image: leigg/hellok8s:log_test_json
          name: hellok8s