#➜ kk describe limits
#Name:       limitrange-for-pod
#Namespace:  default
#  Type        Resource  Min    Max    Default Request  Default Limit  Max Limit/Request Ratio
#  ----        --------  ---    ---    ---------------  -------------  -----------------------
#  Pod         memory    100Mi  300Mi  -                -              -
#  Pod         cpu       100m   200m   -                -              -
apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange-for-pod
  namespace: default
spec:
  limits:
    - type: Pod # 限制Pod的计算资源（Pod内容器的资源总和）
      # 一旦设置 max/min项，再配置Pod的计算资源时，就不能超过这个范围，否则无法创建
      max:
        cpu: "200m"
        memory: "300Mi"
      min:
        cpu: "100m"
        memory: "100Mi"
      # 同时可以设置limit与requests资源的最大比例
      # 对于Pod，这个比例（cpu）的计算方式为：
      #    metadata.namespace 命名空间下：
      #    所有非终止Pod内容器的`resources.limits.cpu`之和  /  所有非终止Pod内容器的`resources.requests.cpu`之和
      # memory同理，所以这个值必须大于等于1。
      maxLimitRequestRatio:
        memory: "2"
        cpu: "2"
