# Pod名称必须是一个合法DNS子域名
# 具体要求：https://kubernetes.io/zh-cn/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names
apiVersion: v1
kind: Pod
metadata:
  name: go-http
  labels:
    app: go
    version: v1
spec:
  containers:
    - name: go-http
      image: leigg/hellok8s:v1