apiVersion: v1
kind: Pod
metadata:
  name: go-http-master
  labels:
    app: "go"
spec:
  nodeName: k8s-master
  containers:
    - name: go-http
      image: leigg/hellok8s:v1
---
apiVersion: v1
kind: Pod
metadata:
  name: go-http-node1
  labels:
    app: "go"
    highcpu: "true"
spec:
  nodeName: k8s-node1
  containers:
    - name: go-http
      image: leigg/hellok8s:v1