# 需要提前创建sa
# 创建secret后，可通过 kk describe secret secret-sa-sample 查看token
# 若要删除，直接删除sa即可（自动删除绑定的secret）
apiVersion: v1
kind: Secret
metadata:
  name: secret-sa-sample
  namespace: default
  annotations:
    kubernetes.io/service-account.name: sa1 # 关联已存在的sa（若sa不存在，则无法创建secret）
type: kubernetes.io/service-account-token # 自动为secret创建token
# 创建后，secret会自动拥有 ca.crt, token数据 (通过kk get secret secret-sa-sample -o yaml 查看)