apiVersion: v1
kind: Secret
metadata:
  name: hellok8s-secret
data:
  DB_PASSWD: cGFzczEyMwo= #  echo pass123 |base64

stringData:
  some.txt: "hello world"

  cert.key: |-
    -----BEGIN OPENSSH PRIVATE KEY-----
    J1a9V50zOAl0k2Fpmy+RDvCy/2LeCZHyWY9MR248Ah2Ko3VywDrevdPIz8bxg9zxqy0+xy
    jbu09sNix9b0IZuZQbbGkw4C4RcAN5HZ4UnWWRfzv2KgtXSdJCPp38hsWH2j9hmlNXLZz0
    EqqtXGJpxjV67NAAAACkxlaWdnQEx1eWk=
    -----END OPENSSH PRIVATE KEY-----

  config.yaml: |-
    username: hellok8s
    password: pass123


# 对于一个大量使用 secret 的集群，禁用修改会带来以下好处
# 1. 保护应用，使之免受意外（不想要的）更新所带来的负面影响。
# 2. 通过大幅降低对 kube-apiserver 的压力提升集群性能， 这是因为系统会关闭对已标记为不可变更的 secret 的监视操作。
# 一旦标记为不可更改，这个操作就不可逆，再想要修改就只能删除并重建 secret
immutable: true
