apiVersion: v1
kind: ConfigMap
metadata:
  name: go-multiroute-v1
data:
  config.yml: |
    routes:
      /route1:
        response: "route1's content"
      /route2:
        response: "route2's content"
      /test_timeout:
        response: "test_timeout's content"
        duration: 3
      /test_limiter:
        response: "test_limiter's content\n"
        duration: 1