elasticsearchHosts: "https://elasticsearch-master:9200"
elasticsearchCertificateSecret: elasticsearch-master-certs
elasticsearchCertificateAuthoritiesFile: ca.crt
elasticsearchCredentialSecret: elasticsearch-master-credentials

# 笔者测试环境内存不足，所以降低一些资源消耗
resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

# 若docker官方仓库以便加速下载
image: "kibana"
imageTag: "8.11.3"


# web端口，默认5601
httpPort: 5601

# 设置 kibana 为中文
kibanaConfig:
  kibana.yml: |
    i18n.locale: "zh-CN"

# 为了方便测试（跳过ingress），service使用NodePort类型
service:
  type: NodePort
  loadBalancerIP: ""
  port: 5601
  nodePort: 30080
