# 测试时部署单节点集群
replicas: 1
minimumMasterNodes: 1

# 使用可加速的镜像仓库
image: "docker.io/library/elasticsearch"
imageTag: "8.5.1"

# statefulSet类型一般都需要设置nodeSelector
nodeSelector:
  kubernetes.io/hostname: k8s-node1

#esConfig:
#  elasticsearch.yml: |
#    xpack.security.enabled: false
#    xpack.security.http.ssl.enabled: false

# 测试时降低requests资源
resources:
  requests:
    cpu: "100m"
    memory: "200M"
  limits:
    cpu: "1000m"
    memory: "2Gi"

# 设置ES密码（留空自动生成）
secret:
  enabled: true
  password: "123"

# 使用http访问es（生产使用https，这里是从简），与上面的 xpack.security.enabled: false 同时生效
protocol: http

# 默认开启持久化（否则数据存在内存中）
persistence:
  enabled: true
volumeClaimTemplate:
  storageClassName: elasticsearch
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi

